- Admin:
    - Hive (Komodo):
        - abbr: HV
          href: https://hive.usmanasad.ca
    - Authentik:
        - abbr: AK
          href: https://auth.usmanasad.ca
    - Beszel:
        - abbr: BZ
          href: https://beszel.usmanasad.ca
